### ISSUE TITLE
PI Version 1.12.2-1.0.9.28 won't download manifest.

### ISSUE THREAD

**Issue by Furious1964** [brandon3055/ProjectIntelligence#28]
I've tried several ways to get this mod to work, but to no avail. Using Twitch's Native Launcher with Java 1.8.0_251 and still nothing. Have tried manually updating the moddocs and manifest and deleting the PI config files with no result.

![Annotation 2020-05-08 031616](https://user-images.githubusercontent.com/2803725/81410773-4bc59b80-910f-11ea-93f5-7d07318bcf37.jpg)

I've port forwarded Minecraft, whitelisted both on my firewall and nothing.

EDIT: Also, I tried adding the VanillaFix Mod and the launcher wouldn't even start. I waited 20 minutes with nothing happening.

**Comment by melodious1963** [comment]
I have the same issue. I tried manually installing the manifest as well.

**Comment by Doedelsander** [comment]
Same

**Comment by brandon3055** [comment]
Please provide a client log. It will be in the minecraft instance folder/logs/latest.log

**Comment by Furious1964** [comment]
Here you go, Sir.
http://www.mediafire.com/file/yfgau0mtv0udmz1/Latest_Log/file

**Comment by FoxMcloud5655** [comment]
The most likely relevant part of the log I'll list below:
```
[17:23:24] [PI-Update-Manager:worker-0/INFO]: [DEV]: ThreadFileDownloader: DL Failed sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[17:23:24] [PI-Update-Manager:worker-0/INFO]: [com.brandon3055.brandonscore.lib.ThreadFileDownloader:run:96]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by Furious1964** [comment]
How can I fix this as I have the latest Java running?

**Comment by brandon3055** [comment]
Damn... That really shouldn't be an issue anymore. Try installing vanillafix and let me know if that fixes it.
https://www.curseforge.com/minecraft/mc-mods/vanillafix

**Comment by Furious1964** [comment]
I attempted to do that before and I couldn't even start minecraft as the game wouldn't load.

**Comment by brandon3055** [comment]
And are you all using the twitch launcher? Can any of you test with multiMC?

**Comment by Furious1964** [comment]
Yes, Twitch Launcher. And I got it to work. Thanks, Mate.

**Comment by CaptJack2883** [comment]
I was also having this issue today, and installing VanillaFix seems to have worked for me. I might suggest that since this is such a big issue, that you could mention VanillaFix as a dependency, or optional dependency?

**Comment by FoxMcloud5655** [comment]
VanillaFix is only a temporary fix for the issue.  It'll get fixed when brandon's computer is fixed.  In other words, eventually :P

**Comment by NordicGamerFE** [comment]
I got the same issue vanillafix dont do it for me and twitch launcher
`Looking for Updates - Failed
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:988)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:986)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:985)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at technicianlp.reauth.VersionChecker.run(VersionChecker.java:36)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jaherron** [comment]
I am having a problem because the code seems to be downloading manifest..json instead of just manifest.json.

**Comment by FoxMcloud5655** [comment]
That's part of how Minecraft renders `j`.  The code is downloading the correct file:
https://github.com/brandon3055/ProjectIntelligence/blob/e09f57a46bfba14afa89db0fb222d71f83202199/src/main/java/com/brandon3055/projectintelligence/docmanagement/PIUpdateManager.java#L35

**Comment by jaherron** [comment]
So I'm probably having the same problem as the person who opened the issue.

**Comment by whitebear60** [comment]
Have the same issue. 
![Screen Shot 2020-07-14 at 14 41 15](https://user-images.githubusercontent.com/42472132/87421854-49386400-c5e0-11ea-9de7-1f465b98e165.png)
Log: https://www.dropbox.com/s/pfs7idt6lybz9ce/pi.latest.log?dl=1

**Comment by coryjreid** [comment]
@brandon3055 I believe this issue is due to misconfigured LetsEncrypt on your web server. Your web server's default website is still online at https://covers1624.net and your https://brandon3055.com is using the cert for the default server URL. This causes a validation failure within Java which then prevents the download. Simply configuring CertBot to manage the cert properly should eliminate the error. ~~VanillaFix isn't a fix for this.~~

Screenshot of the misconfigured cert:
![image](https://user-images.githubusercontent.com/11530109/97818416-8e4fd700-1c5f-11eb-9f7b-0b680f7c26d6.png)

See: https://certbot.eff.org/

**Comment by covers1624** [comment]
@coryjreid You are partially correct, this _was_ originally an issue that was fixed by VanillaFix due to LetsEncrypt certificates not existing on the old Java version that the MinecraftLauncher uses. However, now the issue is partly what you have pointed out, newer Java versions don't care who the certificate is issued to, and obey the Certificates Alternative Names as `brandon3055.com` is one of those, as for older Java versions, they seem to ignore the Alternative Names, even with the LetsEncrypt patch for older Java versions.

I will have to reconfigure my Nginx setup, not happy with how it is at the moment anyway.

**Comment by covers1624** [comment]
`pi.brandon3055.com` should now be providing a certificate issued to `brandon3055.com`, if anyone can verify the issue is fixed on their end that would be fantastic.

**Comment by coryjreid** [comment]
Thanks @covers1624 for hearing me out and teaching me something. You are correct - it is not just the cert mismatch.

I have verified your cert is good. However, the Twitch App (which many of us probably use to play modded for its simplicity in managing mods) forces Java version 1.8.0.51 without some manual effort on the user's part. Even with the updated cert the issue remains without VanillaFix. However, VanillaFix does correct it if choosing to stick with the old Java.

I have confirmed as well that removing VanillaFix and using a more modern Java such as 1.8.0_271 (Oracle) does work as it has the proper CA (just as you described).

**Comment by FoxMcloud5655** [comment]
You've given me a lot more insight into how this all works; thank you.  Now that the cert issue is fixed, we now have a definitive answer on what's going on and I can help others based on this info.

**Comment by covers1624** [comment]
@coryjreid No problem, Unfortunately, as the LetsEncrypt root certificate is not included below Java 8u101, something like VanillaFix or LetsEncryptCraft is required in order to add said root certificate.

However, this isn't an issue in 1.15+ as Forge adds the root certificate itself.

**Comment by coryjreid** [comment]
The alternative is to manually install the latest version of Java 8 and use the JAR Launcher option in the Twitch App. This unlocks the Java version and allows a user to use the Java installed on their system rather than the distributed version.

**Comment by SGZ-Creations** [comment]
I've heard that VanillaFix & one I don't exactly have the name for (fix) is conflicting with each other. at least I've hard that being an 
insane issue if u use ATM 3 Remix at 1.12.2
